name: FlaskKeyring
channels:
    - defaults
dependencies:
    - python=3.12.1
    - flask
    - flask-login
    - flask-mail
    - flask-migrate
    - flask-session
    - flask-sqlalchemy
    - sqlalchemy
    - cryptography
    - python-dotenv
    - psycopg2-binary
    - gunicorn
    - pytz
