"""Updated database schema

Revision ID: 1e6ab27f40d9
Revises: 
Create Date: 2024-10-31 20:30:30.955751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6ab27f40d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
