"""Verify Email table, Folders table, updated passwords table

Revision ID: 40017d49c4cd
Revises: 555b75ead981
Create Date: 2024-01-05 01:07:14.959123

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40017d49c4cd"
down_revision = "555b75ead981"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("passwords", schema=None) as batch_op:
        batch_op.add_column(sa.Column("folder_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_passwords_folder_id", "folders", ["folder_id"], ["id"]
        )

    with op.batch_alter_table("passwords", schema=None) as batch_op:
        batch_op.alter_column("password", type_=sa.Text())

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email_verified", sa.Boolean(), nullable=False, server_default="false"
            )
        )
        batch_op.add_column(
            sa.Column("email_verification_token", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("email_verification_expires_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("email_verification_expires_at")
        batch_op.drop_column("email_verification_token")
        batch_op.drop_column("email_verified")

    with op.batch_alter_table("passwords", schema=None) as batch_op:
        batch_op.drop_constraint("fk_passwords_folder_id", type_="foreignkey")
        batch_op.drop_column("folder_id")

    with op.batch_alter_table("passwords", schema=None) as batch_op:
        batch_op.alter_column("password", type_=sa.String(length=200))

    # ### end Alembic commands ###
