name: Heroku Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install Miniforge
              run: |
                  curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
                  bash Miniforge3-Linux-x86_64.sh -b
                  export PATH="$HOME/miniforge3/bin:$PATH"

            - name: Create Conda environment
              run: conda env create -f environment.yml
              env:
                  CONDA_ALWAYS_YES: "true"

            - name: Find Conda environment path
              id: find_env
              run: echo "::set-output name=env_path::$(conda info --envs | grep FlaskKeyring | awk '{print $1}')"

            - name: Activate Conda environment
              run: conda activate ${{ steps.find_env.outputs.env_path }}
              shell: bash

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Deploy to Heroku
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  HEROKU_APP_NAME: flaskkeyring
              run: |
                  echo "machine api.heroku.com" >> ~/.netrc
                  echo "  login $HEROKU_API_KEY" >> ~/.netrc
                  echo "  password" >> ~/.netrc
                  git push https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
