name: Heroku Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install Conda
              uses: anaconda-inc/setup-miniconda@v2
              with:
                  environment-file: environment.yml

            - name: Create Conda environment
              run: conda env create -f environment.yml

            - name: Activate Conda environment
              run: conda activate FlaskKeyring

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Deploy to Heroku
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  HEROKU_APP_NAME: flaskkeyring
              run: |
                  echo "machine api.heroku.com" >> ~/.netrc
                  echo "  login $HEROKU_API_KEY" >> ~/.netrc
                  echo "  password" >> ~/.netrc
                  git push https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
